installStatePath: ./.yarn/root-install-state.gz
nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.2.4.cjs

# Added fields
defaultProtocol: "npm:"
enableTelemetry: false
defaultLanguageName: node
enableColors: true
enableTimers: true
rcFilename: .yarnrc.yml
progressBarStyle: default
pnpMode: strict