name: Bug report ðŸž
description: >-
  Something is broken and you have a reliable reproduction? Let us know here.
title: '[Bug]: '
labels:
  - bug
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
    validations:
      required: true
  - type: textarea
    id: reproduce
    validations:
      required: true
    attributes:
      label: To Reproduce
      description: >-
        Please create a reproduction by running `npx sb@next repro` and
        following the instructions. Read our
        [documentation](https://storybook.js.org/docs/react/contribute/how-to-reproduce)
        to learn more about creating reproductions.
      placeholder: >-
        Paste your repository path *and* deployed reproduction here.
      render: shell-script
  - type: textarea
    id: system
    validations:
      required: true
    attributes:
      label: System
      description: Please paste the results of `npx sb@next info` here.
      render: shell-script
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.