name: Feature request 💡
description: Suggest an idea for this project
title: '[Feature Request]:'
labels:
  - enhancement
body:
  - type: dropdown
    id: problem
    validations:
      required: true
    attributes:
      label: Is your feature related to problem?
      description: Is your feature related to problem?
      multiple: false
      options:
        - "Yes"
        - "No"
  - type: textarea
    id: describe
    attributes:
      label: Describe the solution you'd like
      description: What would you like to see added to Storybook to solve problem?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Any alternative solutions or features you've considered.
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add things like `mocks`, etc