---
name: "pre-release"

on:
  schedule:
    - cron:  '0 6 * * *' # daily, 6am

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Pre-releaser"
        run: |
          echo "Creating dev release"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest-dev"
          prerelease: true
          title: "Dev Build"
          files: |
            LICENSE.txt